const translations = {
  en: {
    'nav.product':'Product','nav.usecases':'Use cases','nav.technology':'Technology','nav.about':'About','nav.contact':'Pilot with us',
    'hero.eyebrow':'Early-stage EdTech · Vietnam','hero.title':'AI workflows built for the complexity of higher education.','hero.lead':'HieuDaoTao is building reliable AI-assisted workflows for academic regulations, admissions documents, training records, and institutional knowledge.','hero.cta1':'Explore the platform','hero.cta2':'Join our pilot program →','hero.trust':'Prototype stage · Human-in-the-loop by design · Built for Vietnamese higher education contexts',
    'signals.one.kicker':'Focus','signals.one.value':'Higher-education administration','signals.two.kicker':'Stage','signals.two.value':'Prototype & pilot validation','signals.three.kicker':'Core workflow','signals.three.value':'Long-document reasoning','signals.four.kicker':'Region','signals.four.value':'Vietnam first',
    'problem.label':'The problem','problem.title':'Academic administration runs on complex documents, fragmented knowledge, and repetitive checks.','problem.p1.title':'Dense regulations','problem.p1.body':'Policies and academic rules can span hundreds of pages and change across admissions cycles.','problem.p2.title':'Fragmented institutional knowledge','problem.p2.body':'Staff often need to reconcile information from guidelines, spreadsheets, notices, and historical records.','problem.p3.title':'High cost of manual verification','problem.p3.body':'Routine review, cross-checking, and data extraction consume time that could be spent on higher-value student support.',
    'product.label':'What we are building','product.title':'A focused AI workflow layer for university operations.','product.lead':'Our prototype combines long-context document understanding, structured extraction, grounded Q&A, and human review into practical administrative workflows.','product.f1.title':'Document intelligence','product.f1.body':'Analyze long academic regulations, admissions policies, notices, and procedural documents while preserving source references.','product.f1.tag':'Prototype','product.f2.title':'Structured extraction','product.f2.body':'Turn unstructured education documents into structured fields for downstream review, comparison, and reporting.','product.f2.tag':'Prototype','product.f3.title':'Policy-grounded assistant','product.f3.body':'Answer operational questions using institution-provided sources, with citations and explicit uncertainty signals.','product.f3.tag':'In validation','product.f4.title':'Record consistency checks','product.f4.body':'Support staff in identifying mismatches, missing fields, and inconsistencies across administrative records.','product.f4.tag':'Exploration',
    'usecases.label':'Initial use cases','usecases.title':'Starting with workflows where context and traceability matter.','usecases.u1.title':'Admissions policy analysis','usecases.u1.body':'Compare requirements across policy documents, extract eligibility criteria, and support staff with source-grounded answers.','usecases.u2.title':'Academic regulation assistant','usecases.u2.body':'Help staff navigate training regulations, procedural guidelines, and internal knowledge without manually searching every document.','usecases.u3.title':'Administrative data review','usecases.u3.body':'Assist with cross-checking records, surfacing anomalies, and preparing review-ready summaries for human validation.',
    'tech.label':'Technology approach','tech.title':'Designed around grounded outputs, human review, and measurable reliability.','tech.lead':'We are prototyping with Claude for long-context reasoning and document workflows, combined with retrieval, structured outputs, tool use, and evaluation layers.','tech.note':'Concept architecture — implementation evolves as pilots are validated.',
    'principles.label':'Product principles','principles.title':'Useful AI for education requires more than a chatbot.','principles.p1.title':'Grounded by sources','principles.p1.body':'Operational answers should point back to the institutional documents they rely on.','principles.p2.title':'Human-in-the-loop','principles.p2.body':'AI supports staff decisions; it should not silently replace accountable human review.','principles.p3.title':'Evaluation before scale','principles.p3.body':'We aim to test accuracy, traceability, and workflow impact before expanding deployment.','principles.p4.title':'Vietnamese context first','principles.p4.body':'The product is initially designed around Vietnamese academic terminology, regulations, and administrative practices.',
    'about.label':'About HieuDaoTao','about.title':'An early-stage EdTech project focused on practical AI for higher-education operations.','about.p1':'HieuDaoTao is currently in prototype development. We are exploring how modern language models can reduce repetitive document work while improving access to institutional knowledge.','about.p2':'Our current priority is validating a small number of high-value workflows with real academic administration contexts before building a broader production platform.','about.role':'Founder / Project Lead',
    'contact.label':'Pilot program','contact.title':'Interested in testing an AI workflow for academic administration?','contact.body':'We are looking for early conversations with higher-education teams interested in document analysis, policy Q&A, and administrative workflow automation.','contact.email':'hello@hieudaotao.io.vn','contact.linkedin':'Connect on LinkedIn',
    'footer.tagline':'AI-assisted workflows for higher education.','footer.privacy':'Privacy','footer.terms':'Terms','footer.note':'HieuDaoTao is an early-stage project. Product descriptions on this site refer to prototypes and planned capabilities unless stated otherwise.'
  },
  vi: {
    'nav.product':'Sản phẩm','nav.usecases':'Ứng dụng','nav.technology':'Công nghệ','nav.about':'Giới thiệu','nav.contact':'Tham gia pilot',
    'hero.eyebrow':'EdTech giai đoạn sớm · Việt Nam','hero.title':'Quy trình AI được xây dựng cho sự phức tạp của giáo dục đại học.','hero.lead':'HieuDaoTao đang xây dựng các quy trình hỗ trợ bằng AI cho quy chế học vụ, tài liệu tuyển sinh, dữ liệu đào tạo và tri thức nội bộ.','hero.cta1':'Khám phá nền tảng','hero.cta2':'Tham gia chương trình pilot →','hero.trust':'Giai đoạn prototype · Luôn có con người kiểm soát · Thiết kế cho bối cảnh giáo dục đại học Việt Nam',
    'signals.one.kicker':'Trọng tâm','signals.one.value':'Quản trị giáo dục đại học','signals.two.kicker':'Giai đoạn','signals.two.value':'Prototype & kiểm chứng pilot','signals.three.kicker':'Năng lực lõi','signals.three.value':'Suy luận trên tài liệu dài','signals.four.kicker':'Thị trường','signals.four.value':'Ưu tiên Việt Nam',
    'problem.label':'Bài toán','problem.title':'Công tác đào tạo vận hành trên các tài liệu phức tạp, tri thức phân tán và nhiều bước kiểm tra lặp lại.','problem.p1.title':'Quy định dày và phức tạp','problem.p1.body':'Quy chế, hướng dẫn và chính sách có thể dài hàng trăm trang và thay đổi theo từng kỳ tuyển sinh.','problem.p2.title':'Tri thức nội bộ phân tán','problem.p2.body':'Cán bộ thường phải đối chiếu hướng dẫn, bảng tính, thông báo và dữ liệu lịch sử từ nhiều nguồn.','problem.p3.title':'Chi phí kiểm tra thủ công cao','problem.p3.body':'Rà soát, đối chiếu và trích xuất dữ liệu lặp lại làm mất thời gian cho các công việc hỗ trợ người học có giá trị cao hơn.',
    'product.label':'Chúng tôi đang xây dựng','product.title':'Một lớp quy trình AI tập trung cho vận hành đại học.','product.lead':'Prototype kết hợp hiểu tài liệu dài, trích xuất có cấu trúc, hỏi đáp có căn cứ nguồn và bước kiểm tra của con người.','product.f1.title':'Trí tuệ tài liệu','product.f1.body':'Phân tích quy chế đào tạo, chính sách tuyển sinh, thông báo và tài liệu thủ tục dài trong khi vẫn giữ tham chiếu nguồn.','product.f1.tag':'Prototype','product.f2.title':'Trích xuất có cấu trúc','product.f2.body':'Chuyển tài liệu giáo dục phi cấu trúc thành các trường dữ liệu để phục vụ rà soát, so sánh và báo cáo.','product.f2.tag':'Prototype','product.f3.title':'Trợ lý dựa trên chính sách','product.f3.body':'Trả lời câu hỏi nghiệp vụ dựa trên nguồn do đơn vị cung cấp, có dẫn nguồn và tín hiệu mức độ chắc chắn.','product.f3.tag':'Đang kiểm chứng','product.f4.title':'Kiểm tra tính nhất quán dữ liệu','product.f4.body':'Hỗ trợ phát hiện sai khác, trường thiếu và bất nhất giữa các hồ sơ hành chính.','product.f4.tag':'Đang nghiên cứu',
    'usecases.label':'Ứng dụng ban đầu','usecases.title':'Bắt đầu từ các quy trình cần nhiều ngữ cảnh và khả năng truy vết.','usecases.u1.title':'Phân tích chính sách tuyển sinh','usecases.u1.body':'So sánh yêu cầu giữa các văn bản, trích xuất điều kiện và hỗ trợ cán bộ bằng câu trả lời có căn cứ nguồn.','usecases.u2.title':'Trợ lý quy chế đào tạo','usecases.u2.body':'Giúp cán bộ tra cứu quy định, hướng dẫn thủ tục và tri thức nội bộ mà không phải tìm thủ công từng tài liệu.','usecases.u3.title':'Rà soát dữ liệu hành chính','usecases.u3.body':'Hỗ trợ đối chiếu hồ sơ, phát hiện bất thường và tạo bản tóm tắt sẵn sàng cho con người thẩm định.',
    'tech.label':'Cách tiếp cận công nghệ','tech.title':'Thiết kế xoay quanh dữ liệu nguồn, kiểm soát của con người và độ tin cậy có thể đo lường.','tech.lead':'Chúng tôi đang thử nghiệm Claude cho suy luận ngữ cảnh dài và quy trình tài liệu, kết hợp truy xuất, đầu ra có cấu trúc, tool use và lớp đánh giá.','tech.note':'Kiến trúc khái niệm — cách triển khai sẽ tiếp tục thay đổi khi các pilot được kiểm chứng.',
    'principles.label':'Nguyên tắc sản phẩm','principles.title':'AI hữu ích cho giáo dục cần nhiều hơn một chatbot.','principles.p1.title':'Có căn cứ nguồn','principles.p1.body':'Câu trả lời nghiệp vụ cần chỉ ra tài liệu nguồn mà nó dựa vào.','principles.p2.title':'Con người trong vòng kiểm soát','principles.p2.body':'AI hỗ trợ quyết định của cán bộ, không âm thầm thay thế trách nhiệm kiểm tra của con người.','principles.p3.title':'Đánh giá trước khi mở rộng','principles.p3.body':'Chúng tôi ưu tiên kiểm tra độ chính xác, khả năng truy vết và tác động quy trình trước khi triển khai rộng.','principles.p4.title':'Ưu tiên bối cảnh Việt Nam','principles.p4.body':'Sản phẩm ban đầu được thiết kế xoay quanh thuật ngữ, quy định và thực tiễn quản trị giáo dục Việt Nam.',
    'about.label':'Về HieuDaoTao','about.title':'Một dự án EdTech giai đoạn sớm tập trung vào AI thực tiễn cho vận hành giáo dục đại học.','about.p1':'HieuDaoTao hiện ở giai đoạn phát triển prototype. Chúng tôi đang khám phá cách mô hình ngôn ngữ hiện đại có thể giảm công việc tài liệu lặp lại và cải thiện khả năng tiếp cận tri thức nội bộ.','about.p2':'Ưu tiên hiện tại là kiểm chứng một số quy trình có giá trị cao trong bối cảnh quản trị đào tạo thực tế trước khi phát triển thành nền tảng production rộng hơn.','about.role':'Founder / Project Lead',
    'contact.label':'Chương trình pilot','contact.title':'Bạn muốn thử nghiệm một quy trình AI cho công tác quản trị đào tạo?','contact.body':'Chúng tôi muốn trao đổi sớm với các nhóm giáo dục đại học quan tâm đến phân tích tài liệu, hỏi đáp chính sách và tự động hóa quy trình hành chính.','contact.email':'hello@hieudaotao.io.vn','contact.linkedin':'Kết nối LinkedIn',
    'footer.tagline':'Quy trình hỗ trợ bằng AI cho giáo dục đại học.','footer.privacy':'Quyền riêng tư','footer.terms':'Điều khoản','footer.note':'HieuDaoTao là dự án giai đoạn sớm. Các mô tả sản phẩm trên website đề cập đến prototype và năng lực dự kiến trừ khi có ghi chú khác.'
  }
};

let currentLang = localStorage.getItem('hdt-lang') || 'en';
const switcher = document.getElementById('langSwitch');
function applyLanguage(lang){
  currentLang = lang;
  document.documentElement.lang = lang;
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.dataset.i18n;
    if(translations[lang][key]) el.textContent = translations[lang][key];
  });
  switcher.textContent = lang === 'en' ? 'VI' : 'EN';
  localStorage.setItem('hdt-lang', lang);
}
switcher.addEventListener('click',()=>applyLanguage(currentLang === 'en' ? 'vi' : 'en'));
applyLanguage(currentLang);

const header = document.querySelector('.site-header');
window.addEventListener('scroll',()=>header.classList.toggle('scrolled',window.scrollY>10));

const toggle = document.querySelector('.nav-toggle');
const nav = document.querySelector('.nav-links');
toggle.addEventListener('click',()=>{
  const open = nav.classList.toggle('mobile-open');
  toggle.setAttribute('aria-expanded', String(open));
});
nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{
  nav.classList.remove('mobile-open');
  toggle.setAttribute('aria-expanded','false');
}));

const observer = new IntersectionObserver(entries=>{
  entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}})
},{threshold:.12});
document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
